/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_CRITERIA = 'SET_CRITERIA';
// export const SET_CRITERIA_OPTION = 'SET_CRITERIA_OPTION';
export const SET_CRITERIA_CUSTOMIZATION = 'SET_CRITERIA_CUSTOMIZATION';
export const LOANS_SET_ALL = 'LOANS_SET_ALL';
export const LOANS_UPDATE = 'LOANS_UPDATE'; // when?
export const LOANS_FILTER = 'LOANS_FILTER'; // when?
export const LOAN_UPDATE = 'LOAN_UPDATE';
export const PARTNER_DETAILS_UPDATE = 'PARTNER_DETAILS_UPDATE';
export const PARTNER_DETAILS_UPDATE_MANY = 'PARTNER_DETAILS_UPDATE_MANY';
export const LOAN_DETAILS_UPDATE = 'LOAN_DETAILS_UPDATE';
export const LOANS_PROGRESS_UPDATE = 'LOANS_PROGRESS_UPDATE';
export const LOANS_PROGRESS_CLEAR = 'LOANS_PROGRESS_CLEAR';
export const LOAN_DETAILS_UPDATE_MANY = 'LOAN_DETAILS_UPDATE_MANY';
export const BASKET_ADD = 'BASKET_ADD';
export const BASKET_ADD_MANY = 'BASKET_ADD_MANY';
export const BASKET_REMOVE = 'BASKET_REMOVE';
export const BASKET_CLEAR = 'BASKET_CLEAR';
export const BASKET_CLEAN = 'BASKET_CLEAN';
